/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stm32h755xx.h>
#include <stdio.h>
#include <string.h>

#define COMMAND_LED_CTRL	0X50
#define COMMAND_SENSOR_READ	0X51
#define COMMAND_LED_READ	0X52
#define COMMAND_PRINT	0X53
#define COMMAND_ID_READ	0X54


#define LED_ON	1
#define LED_OFF 0

#define ANALOG_PIN0	0
#define ANALOG_PIN1	1
#define ANALOG_PIN2	2
#define ANALOG_PIN3	3
#define ANALOG_PIN4	4

void Delay()
{
	for(uint32_t i = 0; i < 250000; i++);
}

void DelayTime(uint32_t intime)
{
	for(uint32_t i = 0; i < intime; i++);
}

void Led1_init()
{
	Gpio_Handle_t pb0Led;
	pb0Led.pGpiox = GPIOB;
	pb0Led.Gpio_PinConfig.Gpio_PinNumber = GPIO_PIN_NO_0;
	pb0Led.Gpio_PinConfig.Gpio_PinMode = GPIO_MODE_OUT;
	pb0Led.Gpio_PinConfig.Gpio_PinOPType = GPIO_OUT_PP;
	pb0Led.Gpio_PinConfig.Gpio_PinPuPdControl = GPIO_PIN_PU;
	pb0Led.Gpio_PinConfig.Gpio_PinSpeed = GPIO_SPEED_HIGH;
	Gpio_Init(&pb0Led);
}

void Led2_init()
{
	Gpio_Handle_t pe1;
	pe1.pGpiox = GPIOE;
	pe1.Gpio_PinConfig.Gpio_PinNumber = GPIO_PIN_NO_1;
	pe1.Gpio_PinConfig.Gpio_PinMode = GPIO_MODE_OUT;
	pe1.Gpio_PinConfig.Gpio_PinOPType = GPIO_OUT_PP;
	pe1.Gpio_PinConfig.Gpio_PinPuPdControl = GPIO_PIN_PU;
	pe1.Gpio_PinConfig.Gpio_PinSpeed = GPIO_SPEED_HIGH;
	Gpio_Init(&pe1);
}

void Led3_init()
{
	Gpio_Handle_t pb14;
	pb14.pGpiox = GPIOB;
	pb14.Gpio_PinConfig.Gpio_PinMode = GPIO_MODE_OUT;
	pb14.Gpio_PinConfig.Gpio_PinNumber = GPIO_PIN_NO_14;
	pb14.Gpio_PinConfig.Gpio_PinPuPdControl = GPIO_PIN_PU;
	pb14.Gpio_PinConfig.Gpio_PinOPType = GPIO_OUT_PP;
	pb14.Gpio_PinConfig.Gpio_PinSpeed = GPIO_SPEED_HIGH;
	Gpio_Init(&pb14);
}

void Butt15_init()
{
	Gpio_Handle_t pd15;
	pd15.pGpiox = GPIOF;
	pd15.Gpio_PinConfig.Gpio_PinNumber = GPIO_PIN_NO_15;
	pd15.Gpio_PinConfig.Gpio_PinMode = GPIO_MODE_IN;
	pd15.Gpio_PinConfig.Gpio_PinOPType = GPIO_OUT_PP;
	pd15.Gpio_PinConfig.Gpio_PinPuPdControl = GPIO_PIN_PD;
	pd15.Gpio_PinConfig.Gpio_PinSpeed = GPIO_SPEED_FAST;
	Gpio_Init(&pd15);
}

void Spi1_init()
{
	//enable gpio pin
	Gpio_Handle_t pa;
	pa.pGpiox = GPIOA;
	pa.Gpio_PinConfig.Gpio_PinMode = GPIO_MODE_ALTFN;
	pa.Gpio_PinConfig.Gpio_PinAltFunMode = 5;
	pa.Gpio_PinConfig.Gpio_PinOPType = GPIO_OUT_PP;
	pa.Gpio_PinConfig.Gpio_PinPuPdControl = GPIO_PIN_PU;
	pa.Gpio_PinConfig.Gpio_PinSpeed = GPIO_SPEED_FAST;

	pa.Gpio_PinConfig.Gpio_PinNumber = GPIO_PIN_NO_4;
	Gpio_Init(&pa);

	pa.Gpio_PinConfig.Gpio_PinNumber = GPIO_PIN_NO_5;
	Gpio_Init(&pa);

	pa.Gpio_PinConfig.Gpio_PinNumber = GPIO_PIN_NO_7;
	Gpio_Init(&pa);

	pa.Gpio_PinConfig.Gpio_PinPuPdControl = GPIO_PIN_PD;
	pa.Gpio_PinConfig.Gpio_PinNumber = GPIO_PIN_NO_6;
	Gpio_Init(&pa);


	//config spi
	Spi_Handle_t spi1;
	spi1.pSpix = SPI1;
	spi1.SpiConfig.Spi_BusConfig = SPI_BUS_CONFIG_FD;
	spi1.SpiConfig.Spi_CPha = SPI_CPHA_LOW;
	spi1.SpiConfig.Spi_Cpol = SPI_CPOL_LOW;
	spi1.SpiConfig.Spi_DSize = SPI_DSIZE_XBITS(8);
	spi1.SpiConfig.Spi_DeviceMode = SPI_DEVICE_MODE_MASTER;
	spi1.SpiConfig.Spi_SclkSpeed = SPI_SCLK_SPEED_DIV16;
	spi1.SpiConfig.Spi_SsPol = SPI_SSPOL_LOW;
	spi1.SpiConfig.Spi_Ssm = SPI_SSM_DI;

	Spi_Cfig(&spi1, ENABLE);

}

uint8_t Spi_verify_response (uint8_t res)
{
	if(res == 0xf5)
	{
		return 1;
	} else 
	{
		return 0;
	}

}


int main(void)
{
	Rcc_Init();
	Led1_init();
	Led2_init();
	Led3_init();
	Gpio_WriteToOutputPin(GPIOB, GPIO_PIN_NO_0, OFF); //led1
	Gpio_WriteToOutputPin(GPIOE, GPIO_PIN_NO_1, OFF); //led 2
	Butt15_init(); //pf15
	Spi1_init();
	RccSpi1_ClkSw(spi1per_clk);
	uint8_t dummy_write = 0xff;
	uint8_t dummy_read = 0;
	char buff[] = "so bug";
	uint8_t cmd = COMMAND_LED_READ;
	uint8_t ackbyte = 0;
	uint32_t rd = 0;
    /* Loop forever */
	for(;;)
	{
		while( ! Gpio_ReadFromInputPin(GPIOF, GPIO_PIN_NO_15))
		{
			Gpio_WriteToOutputPin(GPIOE, GPIO_PIN_NO_1, OFF);
			Gpio_TogglePin(GPIOB, GPIO_PIN_NO_14);
			Delay();
		}
		Gpio_WriteToOutputPin(GPIOB, GPIO_PIN_NO_14, OFF);
		Gpio_TogglePin(GPIOE, GPIO_PIN_NO_1);
		
		Spi_start(SPI1);
		uint8_t datray[3] = {5, 11, 28};
		uint8_t res = 0;
		Spi_comm(SPI1, &datray, &res ,(sizeof datray / sizeof datray[0]), 0x02);
		Spi_comm(SPI1, (uint8_t*)buff, &res ,strlen(buff), 0x01);

		Spi_end(SPI1);
	};

	return 0;
}
