/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32h755xx.h"
#include "string.h"

/*	port a alternative function 8 will be these
 * pa4 - spi6 nss
 * pa5- spi6 sck
 * pa6- spi6 miso
 * pa7- spi6 mosi
 */

void Spi6_GpioInits(void){
	Gpio_Handle_t spiPins;

	spiPins.pGpiox = GPIOA;
	spiPins.Gpio_PinConfig.Gpio_PinMode = GPIO_MODE_ALTFN;
	spiPins.Gpio_PinConfig.Gpio_PinAltFunMode = 8;
	spiPins.Gpio_PinConfig.Gpio_PinOPType = GPIO_OUT_PP;
	spiPins.Gpio_PinConfig.Gpio_PinPuPdControl = GPIO_NO_PUPD;
	spiPins.Gpio_PinConfig.Gpio_PinSpeed = GPIO_SPEED_FAST;

	// init pin number pa5 for sck
	spiPins.Gpio_PinConfig.Gpio_PinNumber = GPIO_PIN_NO_5;
	Gpio_Init(&spiPins);

	// init pin number pa4 for nss
	//spiPins.Gpio_PinConfig.Gpio_PinNumber = GPIO_PIN_NO_4;
	//Gpio_Init(&spiPins);

	// init pin number pa5 for miso
	//spiPins.Gpio_PinConfig.Gpio_PinNumber = GPIO_PIN_NO_6;
	//Gpio_Init(&spiPins);

	// init pin number pa5 for mosi
	spiPins.Gpio_PinConfig.Gpio_PinNumber = GPIO_PIN_NO_7;
	Gpio_Init(&spiPins);
}

void Spi6_Inits(){
	Spi_Handle_t spiHandle;
	spiHandle.pSpix = SPI6;
	spiHandle.SpiConfig.Spi_BusConfig = SPI_BUS_CONFIG_FD;
	spiHandle.SpiConfig.Spi_DeviceMode = SPI_DEVICE_MODE_MASTER;
	spiHandle.SpiConfig.Spi_SclkSpeed =  SPI_SCLK_SPEED_DIV8;
	spiHandle.SpiConfig.Spi_DSize = SPI_DSIZE_XBITS(8);
	spiHandle.SpiConfig.Spi_Dff = SPI_DFF_MSB;
	spiHandle.SpiConfig.Spi_Cpol = SPI_CPOL_LOW;
	spiHandle.SpiConfig.Spi_CPha = SPI_CPHA_LOW;
	spiHandle.SpiConfig.Spi_Ssm = SPI_SSM_EN;

	Spi_Init(&spiHandle);
}

int main(void)
{
	Spi6_GpioInits();
	Spi6_Inits();

	// enable spi peripheral in peripheral itself
	Spi_PerControl(SPI6, ENABLE);
	// start transmission by setting ctart bit in cr1
	Spi_SetCstart();
	char userBuff[] = "can you be better";
	Spi_SendData(SPI6, (uint8_t*) userBuff, strlen(userBuff));
	Spi_PerControl(SPI6, DISABLE);
    /* Loop forever */
	for(;;);
}
